from pathlib import Path

SARGASSES_PATH = Path("/scratch/shared/sargasses")
NETCDF_PATH = SARGASSES_PATH / "netcdf"
CLOUD_MASK_PATH = SARGASSES_PATH / "cloud_mask"
LABELS_PATH = SARGASSES_PATH / "labels"
OTCI_PATH = SARGASSES_PATH / "png"
ALGAE_MASK_PATH = SARGASSES_PATH / "algae_masks"
RUNS_PATH = SARGASSES_PATH / "runs"
PLOTS_PATH = SARGASSES_PATH / "plot_samples"
CROPS_FILE = SARGASSES_PATH / "crops_for_dataset.csv"
DATASET_PATH = SARGASSES_PATH / "dataset"
TEST_PATH = SARGASSES_PATH / "test"
OPER_MASKS_PATH = TEST_PATH / "olci_oper"
DEV_MASKS_PATH = TEST_PATH / "olci_dev"
MODEL_PATH = SARGASSES_PATH / "model"

SHAPE_IMGS = (4091, 4865)
FULL_DOMAIN = (0, SHAPE_IMGS[0], 0, SHAPE_IMGS[1])
MIN_POSITIVE_PERC = 1
CROP_SIZE = (512, 512)
TRIES = 5
BINARY_THRESHOLD = 0.5
